### ISSUE TITLE
Toggle route Icons on hover or fixed 

### ISSUE THREAD

**Issue by opeolluwa** [opeolluwa/send-file#115]
Checkout the module,
https://github.com/opeolluwa/send-file/blob/master/src/components/AppNavigation.tsx
there are two Icons set, the regular for example, `Cog8ToothIcon` and the solid, `SolidCog8ToothIcon`
The icon changes from regular to solid when a route path is hovered on or clicked

**Comment by Senninseyi** [comment]
Okay seen

**Comment by Senninseyi** [comment]
Done created a PR

**Comment by opeolluwa** [comment]
I've seen it @Senninseyi, I made some reviews, could you attend to that so I can merge the PR. I appreciate you time and effort 💯 Well done :heart:

**Comment by Senninseyi** [comment]
@opeolluwa please where are the reviews so i can see em

**Comment by opeolluwa** [comment]
I've seen it @Senninseyi, I made some reviews, could you attend to that so I can merge the PR. I appreciate you time and effort 💯 Well done :heart:

**Comment by opeolluwa** [comment]
> @opeolluwa please where are the reviews so I can see em

Check the PR thread https://github.com/opeolluwa/send-file/pull/123

**Comment by opeolluwa** [comment]
Hi @Senninseyi!
There is something I'd like you to implement. 
- the routes paths are pretty much tabs, not conventional routes,  
- can we work around setting none as the default? I'd like the color and the Icons to be solid on mouse over event, also, can we animate the transition
 animate the tabs
The Home route is set to the default, In between moving to routes, it displays,

**Comment by Senninseyi** [comment]
I would check it out @opeolluwa

**Comment by opeolluwa** [comment]
thank you

**Comment by opeolluwa** [comment]
resolved
