### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by opeolluwa** [opeolluwa/send-file#120]
Help refactor the readme, the readme should contain the following sections among other things
- **Prerequisite**: - what is required to set the application locally,
- **technology stack** - the technology stack used 
- screenshot
- **environment set up**: how to setup the environment to run the application locally 
- **running the application locally**: various commands to run that application locally 
- **license**: the project is licensed and distributed under MIT
- **roadmap***

* The Roadmap will be updated by @opeolluwa just put the heading

**Comment by akj2018** [comment]
Hi, can I work on this issue ? It's my first time contributing

**Comment by opeolluwa** [comment]
hi, @akj2018 it's great to have you :heart: I recently just worked on the issues but I'm open to refactoring. Please see the #contributing section of the current readme to get started also consider giving the project a star

**Comment by akj2018** [comment]
Thanks @opeolluwa. I would love to contribute and check some other issues.

**Comment by opeolluwa** [comment]
alright great!
Let me know if you need anything
