### ISSUE TITLE
Implement a feature to transverse directories and return the file paths of  matches 

### ISSUE THREAD

**Issue by opeolluwa** [opeolluwa/send-file#85]
- create a `transverse_dir.rs` module in the `core/src/utils` directory 
- in the newly created `transverse_dir.rs`  module, create a data structure, the data structure will contain the following fields

```rs
pub struct File {
    file_name: String, // the file name 
    file_format: String, // the file format, e.g mp4, gif, document 
    file_path: PathBuf, // ex downloads/my-awesome-picture.png
    file_size: String, // the file size calculated in kb, MB, GB, see core/src/utils/mod.rs for a function compute_file_size that helps with this
}
```
- implement a logic to transverse directories and find files, see [ff on crates.io](https://crates.io/crates/ff) for a guide on how this might be implemented 
- return an array of the found files using the created data structure. the returned data should be structured using the CommandData data structure, [defined here ](https://github.com/opeolluwa/send-file/blob/master/core/src/utils/mod.rs#L34)

**Comment by msaboor35** [comment]
I am looking to develop this feature. Before I start, I want to learn about this feature will work. Is it trying to search files for a pattern in the whole file system? or just the home directory? In my opinion, searching over the whole file system does not make sense as it is going to be a very slow operation resulting in a poor user experience. One option is that we can let the user choose where to search and then we can wait if he wants. In this case, it is still better to provide some feedback like a progress bar. However, searching in the home directory seems like a good default for this application.

**Comment by opeolluwa** [comment]
ke

**Comment by msaboor35** [comment]
I was thinking the same actually that we can reuse it in other modules like audio/video, etc.

**Comment by opeolluwa** [comment]
that's correct

**Comment by opeolluwa** [comment]
Thank you for taking the time to contribute and suggest. I appreciate it :heart: 
Please see the [contribution guide](https://github.com/opeolluwa/send-file/blob/master/CONTRIBUTING.md)

**Comment by msaboor35** [comment]
I was thinking the same actually that we can reuse it in other modules like audio/video, etc.
